# Generated by Django 5.1.5 on 2025-05-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentBooking',
        ),
    ]
