# Generated by Django 5.1.5 on 2025-05-19 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_initial'),
        ('hospitalapp', '0020_alter_doctormodel_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_num', to='hospitalapp.slotdivide'),
        ),
    ]
