# Generated by Django 5.1.5 on 2025-05-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_alter_appointmentbooking_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='appointment_date',
            field=models.DateField(default='2025-05-09'),
            preserve_default=False,
        ),
    ]
