# Generated by Django 5.1.5 on 2025-05-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_appointmentbooking_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentbooking',
            old_name='pay_status',
            new_name='status',
        ),
    ]
