# Generated by Django 5.1.5 on 2025-05-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0006_rename_pay_status_appointmentbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
