# Generated by Django 5.1.5 on 2025-05-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0007_alter_appointmentbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='appointment_time',
            field=models.TimeField(null=True),
        ),
    ]
