# Generated by Django 5.1.5 on 2025-05-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
