# Generated by Django 5.1.5 on 2025-05-18 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_departmentmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology'), ('General Surgery', 'General Surgery'), ('ENT', 'ENT'), ('Ophthalmology', 'Ophthalmology'), ('Psychiatry', 'Psychiatry'), ('Radiology', 'Radiology'), ('Oncology', 'Oncology'), ('Urology', 'Urology'), ('Gastroenterology', 'Gastroenterology'), ('Nephrology', 'Nephrology'), ('Pulmonology', 'Pulmonology'), ('Anesthesiology', 'Anesthesiology'), ('Emergency Medicine', 'Emergency Medicine'), ('Plastic Surgery', 'Plastic Surgery'), ('Rheumatology', 'Rheumatology'), ('Endocrinology', 'Endocrinology'), ('Infectious Disease', 'Infectious Disease'), ('Hematology', 'Hematology'), ('Pathology', 'Pathology'), ('Family Medicine', 'Family Medicine'), ('Internal Medicine', 'Internal Medicine'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Otolaryngology', 'Otolaryngology'), ('Other', 'Other')], max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.hospitalmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='DepartmentModel',
        ),
    ]
