# Generated by Django 5.1.5 on 2025-05-18 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_alter_appointmentslot_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slotdivide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.appointmentslot')),
            ],
        ),
    ]
