# Generated by Django 5.1.5 on 2025-05-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0009_appointmentslot_slotdivide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotdivide',
            name='slot',
        ),
        migrations.DeleteModel(
            name='AppointmentSlot',
        ),
        migrations.DeleteModel(
            name='Slotdivide',
        ),
    ]
