# Generated by Django 5.1.5 on 2025-05-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0011_appointmentslot_slotdivide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slotdivide',
        ),
    ]
