# Generated by Django 5.1.5 on 2025-05-18 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0012_delete_slotdivide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slotdivide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.PositiveIntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.appointmentslot')),
            ],
        ),
    ]
