# Generated by Django 5.1.5 on 2025-05-18 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0013_slotdivide'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology'), ('General Surgery', 'General Surgery'), ('ENT', 'ENT'), ('Ophthalmology', 'Ophthalmology'), ('Psychiatry', 'Psychiatry'), ('Radiology', 'Radiology'), ('Oncology', 'Oncology'), ('Urology', 'Urology'), ('Gastroenterology', 'Gastroenterology'), ('Nephrology', 'Nephrology'), ('Pulmonology', 'Pulmonology'), ('Anesthesiology', 'Anesthesiology'), ('Emergency Medicine', 'Emergency Medicine')], max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.hospitalmodel')),
            ],
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.departmentmodel'),
        ),
    ]
