# Generated by Django 5.1.5 on 2025-05-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_delete_appointmentbooking'),
        ('hospitalapp', '0014_departmentmodel_alter_doctormodel_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotdivide',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='departmentmodel',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='doctormodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctormodel',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctormodel',
            name='hospital',
        ),
        migrations.DeleteModel(
            name='AppointmentSlot',
        ),
        migrations.DeleteModel(
            name='Slotdivide',
        ),
        migrations.DeleteModel(
            name='DepartmentModel',
        ),
        migrations.DeleteModel(
            name='DoctorModel',
        ),
        migrations.DeleteModel(
            name='HospitalModel',
        ),
    ]
