# Generated by Django 5.1.5 on 2025-05-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0016_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmodel',
            name='hospital',
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
