# Generated by Django 5.1.5 on 2025-05-18 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0017_remove_departmentmodel_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodel',
            name='hospital',
            field=models.ForeignKey(default=1264, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.hospitalmodel'),
            preserve_default=False,
        ),
    ]
