# Generated by Django 5.1.5 on 2025-05-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0018_departmentmodel_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
