# Generated by Django 5.1.5 on 2025-05-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0020_alter_doctormodel_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmodel',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hospitalmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hospital/'),
        ),
    ]
