# Generated by Django 5.1.5 on 2025-05-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0021_hospitalmodel_description_hospitalmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmodel',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
