# Generated by Django 5.1.5 on 2025-05-18 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_customuser_is_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_doctor',
        ),
    ]
