# Generated by Django 5.1.5 on 2025-05-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
